"""questiontype added

Revision ID: 0818557dbdc2
Revises: 76e43b4da66a
Create Date: 2024-12-22 19:10:58.035921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0818557dbdc2'
down_revision = '76e43b4da66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=False))
        batch_op.drop_column('rder_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rder_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
