"""empty message

Revision ID: 136014fdc41d
Revises: 5214a57dd4c9
Create Date: 2024-11-28 11:01:23.045626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '136014fdc41d'
down_revision = '5214a57dd4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('instructions',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('instructions',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
