"""updated

Revision ID: 17b7af08a320
Revises: 4da9ed77a702
Create Date: 2024-12-25 14:29:34.478459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '17b7af08a320'
down_revision = '4da9ed77a702'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if the answers table exists
    if 'answers' in inspector.get_table_names():
        # Drop foreign key constraints if they exist
        fk_constraints = {fk['name'] for fk in inspector.get_foreign_keys('answers')}
        if 'fk_answers_option_id' in fk_constraints:
            op.drop_constraint('fk_answers_option_id', 'answers', type_='foreignkey')
        if 'fk_answers_question_id' in fk_constraints:
            op.drop_constraint('fk_answers_question_id', 'answers', type_='foreignkey')
        
        with op.batch_alter_table('answers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
            batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
            batch_op.drop_constraint('answers_ibfk_2', type_='foreignkey')
            batch_op.drop_constraint('answers_ibfk_1', type_='foreignkey')
            batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')
            batch_op.drop_column('answer')
            batch_op.drop_column('option_id')

    # Check if 'options' table exists before dropping it
    if 'options' in inspector.get_table_names():
        op.drop_table('options')

    # Check if 'question_types' table exists before dropping index and table
    if 'question_types' in inspector.get_table_names():
        with op.batch_alter_table('question_types', schema=None) as batch_op:
            batch_op.drop_index('type_name')
        op.drop_table('question_types')

    # Check if 'answers' table exists before altering it
    if 'answers' in inspector.get_table_names():
        with op.batch_alter_table('answers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
            batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
            batch_op.drop_constraint('answers_ibfk_2', type_='foreignkey')
            batch_op.drop_constraint('answers_ibfk_1', type_='foreignkey')
            batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')
            batch_op.drop_column('answer')
            batch_op.drop_column('option_id')

    # Check if 'questions' table exists before altering it
    if 'questions' in inspector.get_table_names():
        with op.batch_alter_table('questions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
            batch_op.add_column(sa.Column('format', sa.String(length=50), nullable=False))
            batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))
            batch_op.add_column(sa.Column('shuffle_enabled', sa.Boolean(), nullable=True))
            batch_op.add_column(sa.Column('options_format', sa.String(length=10), nullable=False))
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
            batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
            batch_op.drop_constraint('questions_ibfk_2', type_='foreignkey')
            batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
            batch_op.drop_column('question_type_id')
            batch_op.drop_column('order_number')
            batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('order_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('question_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_2', 'question_types', ['question_type_id'], ['id'])
        batch_op.create_foreign_key('questions_ibfk_1', 'quizzes', ['quiz_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('options_format')
        batch_op.drop_column('shuffle_enabled')
        batch_op.drop_column('score')
        batch_op.drop_column('format')
        batch_op.drop_column('text')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answers_ibfk_1', 'options', ['option_id'], ['id'])
        batch_op.create_foreign_key('answers_ibfk_2', 'questions', ['question_id'], ['id'])
        batch_op.drop_column('order_number')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('image')
        batch_op.drop_column('text')

    # Recreate the options table
    op.create_table('options',
        sa.Column('id', sa.Integer, primary_key=True),
        # ...other columns...
    )
    
    # Recreate foreign key constraints
    op.create_foreign_key('fk_answers_option_id', 'answers', 'options', ['option_id'], ['id'])
    op.create_foreign_key('fk_answers_question_id', 'answers', 'questions', ['question_id'], ['id'])

    op.create_table('question_types',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.create_index('type_name', ['type_name'], unique=True)

    op.create_table('options',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('option', mysql.TEXT(), nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='options_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
