"""image field added

Revision ID: 431186b517bd
Revises: f190105f9814
Create Date: 2024-12-22 13:46:53.281240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431186b517bd'
down_revision = 'f190105f9814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
