"""score added

Revision ID: 4da9ed77a702
Revises: e2db0e9afa95
Create Date: 2024-12-24 19:30:11.310793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da9ed77a702'
down_revision = 'e2db0e9afa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffle_questions_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('shuffle_questions_enabled')

    # ### end Alembic commands ###
