"""questiontype added

Revision ID: 76e43b4da66a
Revises: c041e352df0e
Create Date: 2024-12-22 17:19:11.660766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e43b4da66a'
down_revision = 'c041e352df0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index('ix_quizzes_title')
        batch_op.create_index(batch_op.f('ix_quizzes_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_title'))
        batch_op.create_index('ix_quizzes_title', ['title'], unique=False)

    # ### end Alembic commands ###
