"""end-date added

Revision ID: 92c7862b5f5b
Revises: f2e65802f68d
Create Date: 2025-01-09 13:37:37.686717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c7862b5f5b'
down_revision = 'f2e65802f68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
