"""end-date added

Revision ID: d25786e26234
Revises: 92c7862b5f5b
Create Date: 2025-01-09 13:40:07.498408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd25786e26234'
down_revision = '92c7862b5f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
